title: 개발 블로그
author: vrang-v
email: tlsalsrl0617@gmail.com
description: >-
  2021년부터 시작하는 블로그
baseurl: "/vrang-v.github.io"
url: "https://vrang-v.github.io/"

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

plugins:
  - jekyll-feed
  - jekyll-menus

